env:
  browser: true
  es2021: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - "@typescript-eslint"

settings:
  import/extensions:
    - ".js"
    - ".jsx"
    - ".ts"
    - ".tsx"
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    node:
      extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"

rules:
  "no-console":
    - "error"
  "import/extensions": 0
  "import/no-extraneous-dependencies":
    - "error"
    - "devDependencies": true
  "object-curly-newline": 0
  "no-restricted-exports": 0
  "implicit-arrow-linebreak": 0
  "import/prefer-default-export": 0
  "max-len": [ "error", { "code": 120 } ]
  "@typescript-eslint/no-unused-vars":
    - "error"
  "@typescript-eslint/semi":
    - "error"
  "@typescript-eslint/no-empty-interface":
    - "error"
    - "allowSingleExtends": true
  "no-new": 0
  "import/no-unresolved": 0
  "function-paren-newline": 0
